version: "3.9"

services:
  frontend:
    container_name: "frontend"
    build:
      context: "./frontend/"
      target: "dev-env"
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    ports: 
      - "${FRONT_PORT}:3000"
    environment:
      BACKEND_HOST: ${BACKEND_HOST}
      BACKEND_PORT: ${BACKEND_PORT}
    tty: true
    entrypoint: "bash -c 'yarn install && yarn start'"

  backend:
    container_name: "backend"
    build:
      context: "./backend/"
      target: "dev-env"
    volumes:
      - "./backend:/app"
    ports: 
      - "${BACKEND_PORT}:1323"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    tty: true
    entrypoint: "air"
  
  judge:
    container_name: "judge"
    build:
      context: "./judge/"
      target: "dev-env"
    volumes:
      - "./judge:/app"
    environment:
      BACKEND_HOST: ${BACKEND_HOST}
      BACKEND_PORT: ${BACKEND_PORT}
    tty: true
    entrypoint: "air"

  db:
    container_name: "db"
    image: mysql:8.0.25
    volumes:
      - "db_store:/var/lib/mysql"
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

  redis:
    container_name: "redis"
    image: redis:6.2.5
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"

  nginx:
    container_name: "nginx"
    image: nginx:1.21.3
    volumes:
      - ./docs:/usr/share/nginx/html
    ports:
      - "${API_DOC_PORT}:80"

volumes:
  db_store:
