openapi: "3.0.0"

info:
  title: "Online judge API"
  version: "1.0.0"
  description: "Online judge's backend api reference"

servers:
  - url: "http://localhost:1323"

tags:
  - name: "users"
  - name: "problems"
  - name: "submissions"

paths:
  /register:
    post:
      summary: "Register a user"
      tags:
        - "users"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterData"
      responses:
        "200":
          description: "Successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegisterResponse"
          headers: 
            Set-Cookie:
              schema: 
                type: string
  /login:
    post:
      summary: "Login a user"
      tags:
        - "users"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginData"
      responses:
        "200":
          description: "Successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
  /logout:
    get:
      summary: "Logout a user"
      tags:
        - "users"
      security:
        - session: []
      responses:
        "200":
          description: "Successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LogoutResponse"
  /problems:
    get:
      summary: "Get list of problems"
      tags:
        - "problems"
      security:
        - session: []
      parameters:
        - $ref: "#/components/parameters/Page"
      responses:
        "200":
          description: "Successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetProblemsListResponse"
  /problems/{id}:
    get:
      summary: "Get problem"
      tags:
        - "problems"
      security:
        - session: []
      parameters:
        - $ref: "#/components/parameters/Id"
      responses:
        "200":
          description: "Successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetProblemResponse"
  /submit:
    get:
      summary: "Submit code"
      tags:
        - "submissions"
      security:
        - session: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SubmitData"
      responses:
        "200":
          description: "Successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SubmitResponse"
  /submissions:
    get:
      summary: "Get list of submissions"
      tags:
        - "submissions"
      security:
        - session: []
      parameters:
        - $ref: "#/components/parameters/Page"
      responses:
        "200":
          description: "Successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetSubmissionsListResponse"
  /submissions/{id}:
    get:
      summary: "Get submission"
      tags:
        - "submissions"
      security:
        - session: []
      parameters:
        - $ref: "#/components/parameters/Id"
      responses:
        "200":
          description: "Successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetSubmissionResponse"

components:
  securitySchemes:
    session:
      type: apiKey
      in: cookie
      name: session
  parameters:
    Page:
      name: page
      in: query
      schema:
        type: "integer"
    Id:
      name: id
      in: path
      schema:
        type: "integer"
  schemas:
    ResponseBase:
      required:
        - "success"
        - "error"
      properties:
        success:
          type: "boolean"
        error:
          type: "string"
    RegisterData:
      required:
        - "email"
        - "name"
        - "password"
      properties:
        email:
          type: "string"
        name:
          type: "string"
        password:
          type: "string"
    RegisterResponse:
      allOf:
        - $ref: "#/components/schemas/ResponseBase"
      properties:
        user:
          properties:
            id:
              type: "integer"
            name:
              type: "string"
            role:
              type: "string"
    LoginData:
      required:
        - "name"
        - "password"
      properties:
        name:
          type: "string"
        password:
          type: "string"
    LoginResponse:
      allOf:
        - $ref: "#/components/schemas/ResponseBase"
      properties:
        user:
          properties:
            id:
              type: "integer"
            name:
              type: "string"
            role:
              type: "string"
    LogoutResponse:
      allOf:
        - $ref: "#/components/schemas/ResponseBase"
    GetProblemsListResponse:
      allOf:
        - $ref: "#/components/schemas/ResponseBase"
      properties:
        problems:
          type: "array"
          items:
            type: "object"
            properties:
              id:
                type: "integer"
              name:
                type: "string"
              type:
                type: "string"
              public:
                type: "boolean"
              time_limit:
                type: "integer"
              memory_limit:
                type: "integer"
    GetProblemResponse:
      allOf:
        - $ref: "#/components/schemas/ResponseBase"
      properties:
        problem:
          properties:
            id:
              type: "integer"
            name:
              type: "string"
            type:
              type: "string"
            public:
              type: "boolean"
            time_limit:
              type: "integer"
            memory_limit:
              type: "integer"
            statement:
              type: "string"
            constraints:
              type: "string"
            input_format:
              type: "string"
            output_format:
              type: "string"
    SubmitData:
      required:
        - "problem_id"
        - "language"
        - "code"
      properties:
        problem_id:
          type: "integer"
        language:
          type: "string"
        code:
          type: "string"
    SubmitResponse:
      allOf:
        - $ref: "#/components/schemas/ResponseBase"
      properties:
        id:
          type: "integer"
    GetSubmissionsListResponse:
      allOf:
        - $ref: "#/components/schemas/ResponseBase"
      properties:
        submissions:
          type: "array"
          items:
            type: "object"
            properties:
              id:
                type: "integer"
              problem_id:
                type: "integer"
              problem_name:
                type: "string"
              user_name:
                type: "string"
              public:
                type: "boolean"
              status:
                type: "string"
              score:
                type: "integer"
              execution_time:
                type: "integer"
              execution_memory:
                type: "integer"
              date:
                type: "string"
    GetSubmissionResponse:
      allOf:
        - $ref: "#/components/schemas/ResponseBase"
      properties:
        submission:
          properties:
            id:
              type: "integer"
            problem_id:
              type: "integer"
            problem_name:
              type: "string"
            user_name:
              type: "string"
            public:
              type: "boolean"
            status:
              type: "string"
            score:
              type: "integer"
            execution_time:
              type: "integer"
            execution_memory:
              type: "integer"
            date:
              type: "string"
            code:
              type: "string"
            testsets:
              type: "array"
              items:
                type: "object"
                properties:
                  id:
                    type: "integer"
                  name:
                    type: "string"
                  status:
                    type: "string"
                  score:
                    type: "integer"
            testcases:
              type: "array"
              items:
                type: "object"
                properties:
                  id:
                    type: "integer"
                  name:
                    type: "string"
                  status:
                    type: "string"
                  execution_time:
                    type: "integer"
                  execution_memory:
                    type: "integer"
                  testset_ids:
                    type: "array"
                    items:
                      type: "integer"
